# classifying smoker or non-smoker based on body signal

In [149]:
import numpy
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [150]:
df=pd.read_csv("smoking.csv")

In [151]:
df.head()

,ID,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),...,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar,smoking
0,0,F,40,155,60,81.3,1.2,1.0,1.0,1.0,...,12.9,1.0,0.7,18.0,19.0,27.0,Y,0,Y,0
1,1,F,40,160,60,81.0,0.8,0.6,1.0,1.0,...,12.7,1.0,0.6,22.0,19.0,18.0,Y,0,Y,0
2,2,M,55,170,60,80.0,0.8,0.8,1.0,1.0,...,15.8,1.0,1.0,21.0,16.0,22.0,Y,0,N,1
3,3,M,40,165,70,88.0,1.5,1.5,1.0,1.0,...,14.7,1.0,1.0,19.0,26.0,18.0,Y,0,Y,0
4,4,F,40,155,60,86.0,1.0,1.0,1.0,1.0,...,12.5,1.0,0.6,16.0,14.0,22.0,Y,0,N,0

In [152]:
df.shape

(55692, 27)

In [153]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55692 entries, 0 to 55691
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   55692 non-null  int64
 1   gender               55692 non-null  object
 2   age                  55692 non-null  int64
 3   height(cm)           55692 non-null  int64
 4   weight(kg)           55692 non-null  int64
 5   waist(cm)            55692 non-null  float64
 6   eyesight(left)       55692 non-null  float64
 7   eyesight(right)      55692 non-null  float64
 8   hearing(left)        55692 non-null  float64
 9   hearing(right)       55692 non-null  float64
 10  systolic             55692 non-null  float64
 11  relaxation           55692 non-null  float64
 12  fasting blood sugar  55692 non-null  float64
 13  Cholesterol          55692 non-null  float64
 14  triglyceride         55692 non-null  float64
 15  HDL                  55692 non-null  float64
 16  LDL                  55692 non-null  float64
 17  hemoglobin           55692 non-null  float64
 18  Urine protein        55692 non-null  float64
 19  serum creatinine     55692 non-null  float64
 20  AST                  55692 non-null  float64
 21  ALT                  55692 non-null  float64
 22  Gtp                  55692 non-null  float64
 23  oral                 55692 non-null  object
 24  dental caries        55692 non-null  int64
 25  tartar               55692 non-null  object
 26  smoking              55692 non-null  int64
dtypes: float64(18), int64(6), object(3)
memory usage: 11.5+ MB

In [154]:
df.describe()

,ID,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),systolic,...,HDL,LDL,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,dental caries,smoking
count,55692.000000,55692.000000,55692.000000,55692.000000,55692.000000,55692.000000,55692.000000,55692.000000,55692.000000,55692.000000,...,55692.000000,55692.000000,55692.000000,55692.000000,55692.000000,55692.000000,55692.000000,55692.000000,55692.000000,55692.000000
mean,27845.500000,44.182917,164.649321,65.864936,82.046418,1.012623,1.007443,1.025587,1.026144,121.494218,...,57.290347,114.964501,14.622592,1.087212,0.885738,26.182935,27.036037,39.952201,0.213334,0.367288
std,16077.039933,12.071418,9.194597,12.820306,9.274223,0.486873,0.485964,0.157902,0.159564,13.675989,...,14.738963,40.926476,1.564498,0.404882,0.221524,19.355460,30.947853,50.290539,0.409665,0.482070
min,0.000000,20.000000,130.000000,30.000000,51.000000,0.100000,0.100000,1.000000,1.000000,71.000000,...,4.000000,1.000000,4.900000,1.000000,0.100000,6.000000,1.000000,1.000000,0.000000,0.000000
25%,13922.750000,40.000000,160.000000,55.000000,76.000000,0.800000,0.800000,1.000000,1.000000,112.000000,...,47.000000,92.000000,13.600000,1.000000,0.800000,19.000000,15.000000,17.000000,0.000000,0.000000
50%,27845.500000,40.000000,165.000000,65.000000,82.000000,1.000000,1.000000,1.000000,1.000000,120.000000,...,55.000000,113.000000,14.800000,1.000000,0.900000,23.000000,21.000000,25.000000,0.000000,0.000000
75%,41768.250000,55.000000,170.000000,75.000000,88.000000,1.200000,1.200000,1.000000,1.000000,130.000000,...,66.000000,136.000000,15.800000,1.000000,1.000000,28.000000,31.000000,43.000000,0.000000,1.000000
max,55691.000000,85.000000,190.000000,135.000000,129.000000,9.900000,9.900000,2.000000,2.000000,240.000000,...,618.000000,1860.000000,21.100000,6.000000,11.600000,1311.000000,2914.000000,999.000000,1.000000,1.000000

In [155]:
from sklearn.preprocessing import LabelEncoder

In [156]:
le=LabelEncoder()

In [157]:
df['oral']=le.fit_transform(df.oral)
df['tartar']=le.fit_transform(df.tartar)
df['gender']=le.fit_transform(df.gender)

In [158]:
df.head()

,ID,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),...,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar,smoking
0,0,0,40,155,60,81.3,1.2,1.0,1.0,1.0,...,12.9,1.0,0.7,18.0,19.0,27.0,0,0,1,0
1,1,0,40,160,60,81.0,0.8,0.6,1.0,1.0,...,12.7,1.0,0.6,22.0,19.0,18.0,0,0,1,0
2,2,1,55,170,60,80.0,0.8,0.8,1.0,1.0,...,15.8,1.0,1.0,21.0,16.0,22.0,0,0,0,1
3,3,1,40,165,70,88.0,1.5,1.5,1.0,1.0,...,14.7,1.0,1.0,19.0,26.0,18.0,0,0,1,0
4,4,0,40,155,60,86.0,1.0,1.0,1.0,1.0,...,12.5,1.0,0.6,16.0,14.0,22.0,0,0,0,0

In [159]:
target=df['smoking']
features=df.drop(df[['ID','smoking']],axis=1)

In [160]:
features

,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),systolic,...,LDL,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar
0,0,40,155,60,81.3,1.2,1.0,1.0,1.0,114.0,...,126.0,12.9,1.0,0.7,18.0,19.0,27.0,0,0,1
1,0,40,160,60,81.0,0.8,0.6,1.0,1.0,119.0,...,127.0,12.7,1.0,0.6,22.0,19.0,18.0,0,0,1
2,1,55,170,60,80.0,0.8,0.8,1.0,1.0,138.0,...,151.0,15.8,1.0,1.0,21.0,16.0,22.0,0,0,0
3,1,40,165,70,88.0,1.5,1.5,1.0,1.0,100.0,...,226.0,14.7,1.0,1.0,19.0,26.0,18.0,0,0,1
4,0,40,155,60,86.0,1.0,1.0,1.0,1.0,120.0,...,107.0,12.5,1.0,0.6,16.0,14.0,22.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55687,0,40,170,65,75.0,0.9,0.9,1.0,1.0,110.0,...,118.0,12.3,1.0,0.6,14.0,7.0,10.0,0,1,1
55688,0,45,160,50,70.0,1.2,1.2,1.0,1.0,101.0,...,79.0,14.0,1.0,0.9,20.0,12.0,14.0,0,0,1
55689,0,55,160,50,68.5,1.0,1.2,1.0,1.0,117.0,...,63.0,12.4,1.0,0.5,17.0,11.0,12.0,0,0,0
55690,1,60,165,60,78.0,0.8,1.0,1.0,1.0,133.0,...,146.0,14.4,1.0,0.7,20.0,19.0,18.0,0,0,0
55691,1,55,160,65,85.0,0.9,0.7,1.0,1.0,124.0,...,150.0,15.0,1.0,0.8,26.0,29.0,41.0,0,0,1

In [161]:
from sklearn.model_selection import train_test_split

In [231]:
X_train,X_test,y_train,y_test=train_test_split(features,target,test_size=0.2)

In [232]:
from sklearn.linear_model import LogisticRegression

In [233]:
model=LogisticRegression()

In [234]:
model.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [235]:
predicted=model.predict(X_test)

In [236]:
model.score(X_test,y_test)

0.7467456683723853

In [237]:
from sklearn import metrics

In [238]:
metrics.accuracy_score(y_test,predicted)

0.7467456683723853

In [239]:
from sklearn.ensemble import RandomForestClassifier

In [240]:
rf=RandomForestClassifier()

In [241]:
rf.fit(X_train,y_train)

RandomForestClassifier()

In [242]:
rf.predict(X_test)

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [243]:
rf.score(X_test,y_test)

0.8348146153155579

In [244]:
import xgboost as xgb

In [245]:
XB = xgb.XGBClassifier()
XB.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [246]:
XB.predict(X_test)

array([0, 0, 0, ..., 1, 1, 1])

In [247]:
XB.score(X_test,y_test)

0.7878624652123171

In [248]:
from sklearn.neighbors import KNeighborsClassifier

In [249]:
kn=KNeighborsClassifier(n_neighbors=2)

In [250]:
kn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=2)

In [251]:
kn.score(X_test,y_test)

0.7301373552383518

In [188]:
df.isna().sum()

ID                     0
gender                 0
age                    0
height(cm)             0
weight(kg)             0
waist(cm)              0
eyesight(left)         0
eyesight(right)        0
hearing(left)          0
hearing(right)         0
systolic               0
relaxation             0
fasting blood sugar    0
Cholesterol            0
triglyceride           0
HDL                    0
LDL                    0
hemoglobin             0
Urine protein          0
serum creatinine       0
AST                    0
ALT                    0
Gtp                    0
oral                   0
dental caries          0
tartar                 0
smoking                0
dtype: int64

In [252]:
from sklearn.preprocessing import MinMaxScaler

In [253]:
scaler=MinMaxScaler()

In [254]:
scale = ['age', 'height(cm)', 'weight(kg)', 'waist(cm)', 'eyesight(left)',
       'eyesight(right)', 'hearing(left)', 'hearing(right)', 'systolic',
       'relaxation', 'fasting blood sugar', 'Cholesterol', 'triglyceride',
       'HDL', 'LDL', 'hemoglobin', 'Urine protein', 'serum creatinine', 'AST',
       'ALT', 'Gtp', 'dental caries']

In [255]:
df[scale] = scaler.fit_transform(df[scale])

In [256]:
df

,ID,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),...,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar,smoking
0,0,0,0.307692,0.416667,0.285714,0.388462,0.112245,0.091837,0.0,0.0,...,0.493827,0.0,0.052174,0.009195,0.006179,0.026052,0.0,0.0,1.0,0
1,1,0,0.307692,0.500000,0.285714,0.384615,0.071429,0.051020,0.0,0.0,...,0.481481,0.0,0.043478,0.012261,0.006179,0.017034,0.0,0.0,1.0,0
2,2,1,0.538462,0.666667,0.285714,0.371795,0.071429,0.071429,0.0,0.0,...,0.672840,0.0,0.078261,0.011494,0.005149,0.021042,0.0,0.0,0.0,1
3,3,1,0.307692,0.583333,0.380952,0.474359,0.142857,0.142857,0.0,0.0,...,0.604938,0.0,0.078261,0.009962,0.008582,0.017034,0.0,0.0,1.0,0
4,4,0,0.307692,0.416667,0.285714,0.448718,0.091837,0.091837,0.0,0.0,...,0.469136,0.0,0.043478,0.007663,0.004463,0.021042,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55687,55676,0,0.307692,0.666667,0.333333,0.307692,0.081633,0.081633,0.0,0.0,...,0.456790,0.0,0.043478,0.006130,0.002060,0.009018,0.0,1.0,1.0,0
55688,55681,0,0.384615,0.500000,0.190476,0.243590,0.112245,0.112245,0.0,0.0,...,0.561728,0.0,0.069565,0.010728,0.003776,0.013026,0.0,0.0,1.0,0
55689,55683,0,0.538462,0.500000,0.190476,0.224359,0.091837,0.112245,0.0,0.0,...,0.462963,0.0,0.034783,0.008429,0.003433,0.011022,0.0,0.0,0.0,0
55690,55684,1,0.615385,0.583333,0.285714,0.346154,0.071429,0.091837,0.0,0.0,...,0.586420,0.0,0.052174,0.010728,0.006179,0.017034,0.0,0.0,0.0,0
55691,55691,1,0.538462,0.500000,0.333333,0.435897,0.081633,0.061224,0.0,0.0,...,0.623457,0.0,0.060870,0.015326,0.009612,0.040080,0.0,0.0,1.0,1

In [257]:
target=df['smoking']
features=df.drop(df[['ID','smoking']],axis=1)

In [258]:
features

,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),systolic,...,LDL,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar
0,0,0.307692,0.416667,0.285714,0.388462,0.112245,0.091837,0.0,0.0,0.254438,...,0.067240,0.493827,0.0,0.052174,0.009195,0.006179,0.026052,0.0,0.0,1.0
1,0,0.307692,0.500000,0.285714,0.384615,0.071429,0.051020,0.0,0.0,0.284024,...,0.067778,0.481481,0.0,0.043478,0.012261,0.006179,0.017034,0.0,0.0,1.0
2,1,0.538462,0.666667,0.285714,0.371795,0.071429,0.071429,0.0,0.0,0.396450,...,0.080689,0.672840,0.0,0.078261,0.011494,0.005149,0.021042,0.0,0.0,0.0
3,1,0.307692,0.583333,0.380952,0.474359,0.142857,0.142857,0.0,0.0,0.171598,...,0.121033,0.604938,0.0,0.078261,0.009962,0.008582,0.017034,0.0,0.0,1.0
4,0,0.307692,0.416667,0.285714,0.448718,0.091837,0.091837,0.0,0.0,0.289941,...,0.057020,0.469136,0.0,0.043478,0.007663,0.004463,0.021042,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55687,0,0.307692,0.666667,0.333333,0.307692,0.081633,0.081633,0.0,0.0,0.230769,...,0.062937,0.456790,0.0,0.043478,0.006130,0.002060,0.009018,0.0,1.0,1.0
55688,0,0.384615,0.500000,0.190476,0.243590,0.112245,0.112245,0.0,0.0,0.177515,...,0.041958,0.561728,0.0,0.069565,0.010728,0.003776,0.013026,0.0,0.0,1.0
55689,0,0.538462,0.500000,0.190476,0.224359,0.091837,0.112245,0.0,0.0,0.272189,...,0.033351,0.462963,0.0,0.034783,0.008429,0.003433,0.011022,0.0,0.0,0.0
55690,1,0.615385,0.583333,0.285714,0.346154,0.071429,0.091837,0.0,0.0,0.366864,...,0.077999,0.586420,0.0,0.052174,0.010728,0.006179,0.017034,0.0,0.0,0.0
55691,1,0.538462,0.500000,0.333333,0.435897,0.081633,0.061224,0.0,0.0,0.313609,...,0.080151,0.623457,0.0,0.060870,0.015326,0.009612,0.040080,0.0,0.0,1.0

In [259]:
from sklearn.model_selection import train_test_split

In [264]:
X_train,X_test,y_train,y_test=train_test_split(features,target,test_size=0.2)

In [265]:
rf=RandomForestClassifier()

In [266]:
rf.fit(X_train,y_train)

RandomForestClassifier()

In [267]:
rf.score(X_test,y_test)

0.8396624472573839

In [268]:
k=LogisticRegression()
k.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [269]:
k.score(X_test,y_test)

0.7408205404434869